import Head from "next/head";

import { Hero, Features } from "@/components";

import styles from "@/styles/Home.module.css";

export default function Home() {
	return (
		<>
			<Head>
				<title>Muum Store - Open Source E-Commerce Boilerplate</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={`${styles.main}`}>
				<Hero />
				<Features />
			</main>
		</>
	);
}
